name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: multiarm-bandit
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci # maybe use npm install?

      - name: Run lint
        run: npm run lint -- --max-warnings=0

      - name: Run build
        run: npm run build --if-present

      - name: Run tests
        run: npm test
